/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COLON = 1,
  sym_zinc_block = 2,
  sym_trio_block = 3,
  sym_list_block = 4,
  sym_dict_block = 5,
  sym_separator = 6,
  sym_name = 7,
  sym_ref = 8,
  sym_symbol = 9,
  sym_str = 10,
  sym_uri = 11,
  sym_date_time = 12,
  sym_date = 13,
  sym_time = 14,
  sym_number = 15,
  anon_sym_true = 16,
  anon_sym_false = 17,
  anon_sym_T = 18,
  anon_sym_F = 19,
  sym_na = 20,
  sym_remove = 21,
  sym_list = 22,
  sym_dict = 23,
  sym_xstr = 24,
  sym_raw = 25,
  sym_indented_text = 26,
  sym_comment = 27,
  sym__newline = 28,
  sym_source_file = 29,
  sym_record = 30,
  sym__line = 31,
  sym_tag = 32,
  sym_block_tag = 33,
  sym__scalar = 34,
  sym_bool = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_source_file_repeat2 = 37,
  aux_sym_record_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COLON] = ":",
  [sym_zinc_block] = "zinc_block",
  [sym_trio_block] = "trio_block",
  [sym_list_block] = "list_block",
  [sym_dict_block] = "dict_block",
  [sym_separator] = "separator",
  [sym_name] = "name",
  [sym_ref] = "ref",
  [sym_symbol] = "symbol",
  [sym_str] = "str",
  [sym_uri] = "uri",
  [sym_date_time] = "date_time",
  [sym_date] = "date",
  [sym_time] = "time",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_T] = "T",
  [anon_sym_F] = "F",
  [sym_na] = "na",
  [sym_remove] = "remove",
  [sym_list] = "list",
  [sym_dict] = "dict",
  [sym_xstr] = "xstr",
  [sym_raw] = "raw",
  [sym_indented_text] = "indented_text",
  [sym_comment] = "comment",
  [sym__newline] = "_newline",
  [sym_source_file] = "source_file",
  [sym_record] = "record",
  [sym__line] = "_line",
  [sym_tag] = "tag",
  [sym_block_tag] = "block_tag",
  [sym__scalar] = "_scalar",
  [sym_bool] = "bool",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_record_repeat1] = "record_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_zinc_block] = sym_zinc_block,
  [sym_trio_block] = sym_trio_block,
  [sym_list_block] = sym_list_block,
  [sym_dict_block] = sym_dict_block,
  [sym_separator] = sym_separator,
  [sym_name] = sym_name,
  [sym_ref] = sym_ref,
  [sym_symbol] = sym_symbol,
  [sym_str] = sym_str,
  [sym_uri] = sym_uri,
  [sym_date_time] = sym_date_time,
  [sym_date] = sym_date,
  [sym_time] = sym_time,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_T] = anon_sym_T,
  [anon_sym_F] = anon_sym_F,
  [sym_na] = sym_na,
  [sym_remove] = sym_remove,
  [sym_list] = sym_list,
  [sym_dict] = sym_dict,
  [sym_xstr] = sym_xstr,
  [sym_raw] = sym_raw,
  [sym_indented_text] = sym_indented_text,
  [sym_comment] = sym_comment,
  [sym__newline] = sym__newline,
  [sym_source_file] = sym_source_file,
  [sym_record] = sym_record,
  [sym__line] = sym__line,
  [sym_tag] = sym_tag,
  [sym_block_tag] = sym_block_tag,
  [sym__scalar] = sym__scalar,
  [sym_bool] = sym_bool,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_record_repeat1] = aux_sym_record_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_zinc_block] = {
    .visible = true,
    .named = true,
  },
  [sym_trio_block] = {
    .visible = true,
    .named = true,
  },
  [sym_list_block] = {
    .visible = true,
    .named = true,
  },
  [sym_dict_block] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ref] = {
    .visible = true,
    .named = true,
  },
  [sym_symbol] = {
    .visible = true,
    .named = true,
  },
  [sym_str] = {
    .visible = true,
    .named = true,
  },
  [sym_uri] = {
    .visible = true,
    .named = true,
  },
  [sym_date_time] = {
    .visible = true,
    .named = true,
  },
  [sym_date] = {
    .visible = true,
    .named = true,
  },
  [sym_time] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_T] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_F] = {
    .visible = true,
    .named = false,
  },
  [sym_na] = {
    .visible = true,
    .named = true,
  },
  [sym_remove] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_dict] = {
    .visible = true,
    .named = true,
  },
  [sym_xstr] = {
    .visible = true,
    .named = true,
  },
  [sym_raw] = {
    .visible = true,
    .named = true,
  },
  [sym_indented_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_record] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_block_tag] = {
    .visible = true,
    .named = true,
  },
  [sym__scalar] = {
    .visible = false,
    .named = true,
  },
  [sym_bool] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_record_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_kind = 1,
  field_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_kind] = "kind",
  [field_name] = "name",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 0},
    {field_value, 2},
  [3] =
    {field_kind, 2},
    {field_name, 0},
    {field_value, 3},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(61);
      ADVANCE_MAP(
        '\n', 214,
        '\r', 2,
        '"', 6,
        '-', 71,
        '/', 23,
        '0', 122,
        ':', 62,
        '@', 55,
        'F', 155,
        'I', 13,
        'N', 11,
        'R', 159,
        'T', 153,
        'Z', 16,
        '[', 67,
        '^', 56,
        '`', 30,
        'f', 86,
        't', 90,
        '{', 68,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(123);
      if (('A' <= lookahead && lookahead <= 'Y')) ADVANCE(20);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(214);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 214,
        '\r', 2,
        '"', 6,
        '-', 71,
        '/', 23,
        '0', 122,
        ':', 62,
        '@', 55,
        'F', 155,
        'I', 13,
        'N', 11,
        'R', 159,
        'T', 153,
        'Z', 16,
        '[', 67,
        '^', 56,
        '`', 30,
        'f', 86,
        't', 90,
        '{', 68,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(123);
      if (('A' <= lookahead && lookahead <= 'Y')) ADVANCE(20);
      if (('_' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(214);
      if (lookahead == '\r') ADVANCE(1);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 214,
        '\r', 4,
        '"', 6,
        '-', 24,
        '/', 179,
        '0', 128,
        '@', 55,
        'F', 156,
        'I', 169,
        'N', 167,
        'R', 160,
        'T', 154,
        'Z', 172,
        '[', 67,
        '^', 56,
        '`', 30,
        'f', 182,
        't', 186,
        '{', 68,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(4);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(129);
      if (('A' <= lookahead && lookahead <= 'Y')) ADVANCE(176);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(213);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(218);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '-') ADVANCE(85);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ':') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(97);
      if (lookahead == '\\') ADVANCE(58);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == '"') ADVANCE(94);
      if (lookahead == '\\') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 9:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ':') ADVANCE(65);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == ':') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 11:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'A') ADVANCE(157);
      if (lookahead == 'a') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'F') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 13:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'N') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 14:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'N') ADVANCE(118);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 15:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'c') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 16:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 17:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'i') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 18:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'n') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'o') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 20:
      if (lookahead == '(') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      if (lookahead == ')') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(21);
      END_STATE();
    case 22:
      if (lookahead == '-') ADVANCE(48);
      END_STATE();
    case 23:
      if (lookahead == '/') ADVANCE(217);
      END_STATE();
    case 24:
      if (lookahead == '0') ADVANCE(125);
      if (lookahead == 'I') ADVANCE(28);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 25:
      if (lookahead == ':') ADVANCE(50);
      END_STATE();
    case 26:
      if (lookahead == ':') ADVANCE(52);
      END_STATE();
    case 27:
      if (lookahead == 'F') ADVANCE(117);
      END_STATE();
    case 28:
      if (lookahead == 'N') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == ']') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 30:
      if (lookahead == '`') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(30);
      END_STATE();
    case 31:
      if (lookahead == '}') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    case 32:
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(113);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(111);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(22);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(109);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(101);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(105);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(99);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(103);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(39);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(40);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(41);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 55:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '~') ADVANCE(95);
      END_STATE();
    case 56:
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '~') ADVANCE(96);
      END_STATE();
    case 57:
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 58:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 59:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(8);
      END_STATE();
    case 60:
      if (eof) ADVANCE(61);
      if (lookahead == '\n') ADVANCE(218);
      if (lookahead == '\r') ADVANCE(5);
      if (lookahead == '-') ADVANCE(85);
      if (lookahead == '/') ADVANCE(23);
      if (lookahead == ':') ADVANCE(62);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(60);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_zinc_block);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_zinc_block);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_trio_block);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_trio_block);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_list_block);
      if (lookahead == ']') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_dict_block);
      if (lookahead == '}') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '.') ADVANCE(79);
      if (lookahead == '_') ADVANCE(70);
      if (lookahead == 'x') ADVANCE(82);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '.') ADVANCE(79);
      if (lookahead == '_') ADVANCE(70);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '0') ADVANCE(69);
      if (lookahead == 'I') ADVANCE(73);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == 'F') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == 'N') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '_') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(74);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '_') ADVANCE(83);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '_') ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '_') ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_separator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_separator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_separator);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(84);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_separator);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(74);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead == '$' ||
          lookahead == '%' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_separator);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'a') ADVANCE(89);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(149);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'e') ADVANCE(151);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'l') ADVANCE(91);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'r') ADVANCE(92);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 's') ADVANCE(88);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_name);
      if (lookahead == 'u') ADVANCE(87);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_ref);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_ref);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '~') ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_symbol);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          lookahead == '~') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_str);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_uri);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '.') ADVANCE(43);
      if (lookahead == 'Z') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(54);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '.') ADVANCE(200);
      if (lookahead == 'Z') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(189);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(211);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == ':') ADVANCE(51);
      if (lookahead == 'Z') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(54);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == ':') ADVANCE(208);
      if (lookahead == 'Z') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(189);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(211);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == 'Z') ADVANCE(105);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(54);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(103);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == 'Z') ADVANCE(106);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(189);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(211);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(32);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(189);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(107);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_date_time);
      if (lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_date);
      if (lookahead == 'T') ADVANCE(49);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_date);
      if (lookahead == 'T') ADVANCE(206);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == '.') ADVANCE(37);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == '.') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(46);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_time);
      if (lookahead == ':') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_time);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_time);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '(') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '(') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '_') ADVANCE(126);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '-') ADVANCE(204);
      if (lookahead == '.') ADVANCE(190);
      if (lookahead == '_') ADVANCE(131);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '_') ADVANCE(126);
      if (lookahead == 'x') ADVANCE(145);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '_') ADVANCE(126);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == ':') ADVANCE(45);
      if (lookahead == '_') ADVANCE(126);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '_') ADVANCE(126);
      if (lookahead == 'x') ADVANCE(145);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '_') ADVANCE(126);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(33);
      if (lookahead == '_') ADVANCE(126);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(190);
      if (lookahead == ':') ADVANCE(202);
      if (lookahead == '_') ADVANCE(131);
      if (lookahead == 'x') ADVANCE(146);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(190);
      if (lookahead == ':') ADVANCE(202);
      if (lookahead == '_') ADVANCE(131);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(190);
      if (lookahead == ':') ADVANCE(202);
      if (lookahead == '_') ADVANCE(131);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(190);
      if (lookahead == '_') ADVANCE(131);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(190);
      if (lookahead == '_') ADVANCE(131);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(133);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(133);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(57);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(141);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(57);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(143);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(137);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(137);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(212);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(142);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(212);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(144);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(201);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(147);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          lookahead == '_') ADVANCE(148);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(133);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(137);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('G' <= lookahead && lookahead <= 'Z') ||
          ('g' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '$' ||
          lookahead == '%' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(147);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '$' ||
          lookahead == '%' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(93);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(anon_sym_T);
      if (lookahead == '(') ADVANCE(21);
      if (lookahead == 'r') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(anon_sym_T);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'r') ADVANCE(173);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_F);
      if (lookahead == '(') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_F);
      if (lookahead == '(') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_na);
      if (lookahead == '(') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_na);
      if (lookahead == '(') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_remove);
      if (lookahead == '(') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_remove);
      if (lookahead == '(') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_list);
      if (lookahead == ']') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(29);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_dict);
      if (lookahead == '}') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(31);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_xstr);
      if (lookahead == ')') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(21);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_xstr);
      if (lookahead == ')') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(177);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == ':') ADVANCE(66);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == ':') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'A') ADVANCE(158);
      if (lookahead == 'a') ADVANCE(170);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'F') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'N') ADVANCE(168);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'N') ADVANCE(119);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'c') ADVANCE(166);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(174);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'i') ADVANCE(175);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'n') ADVANCE(171);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (lookahead == 'o') ADVANCE(165);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '(') ADVANCE(177);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == ')') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(177);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '-') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '/') ADVANCE(217);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == ':') ADVANCE(207);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == ':') ADVANCE(209);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == 'a') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == 'e') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == 'e') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == 'l') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == 'r') ADVANCE(188);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == 's') ADVANCE(184);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == 'u') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(189);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(192);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(198);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_raw);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(210);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead == '$' ||
          lookahead == '%' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z') ||
          (0xb0 <= lookahead && lookahead <= 0xffff)) ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_raw);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(213);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_indented_text);
      if (lookahead == '\n') ADVANCE(214);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(215);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(3);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_indented_text);
      if (lookahead == '\n') ADVANCE(214);
      if (lookahead == '\r') ADVANCE(216);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(215);
      if (lookahead != 0) ADVANCE(216);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_indented_text);
      if (lookahead == '\n') ADVANCE(214);
      if (lookahead == '\r') ADVANCE(216);
      if (lookahead != 0) ADVANCE(216);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(217);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 60},
  [2] = {.lex_state = 4},
  [3] = {.lex_state = 60},
  [4] = {.lex_state = 60},
  [5] = {.lex_state = 60},
  [6] = {.lex_state = 60},
  [7] = {.lex_state = 60},
  [8] = {.lex_state = 60},
  [9] = {.lex_state = 60},
  [10] = {.lex_state = 60},
  [11] = {.lex_state = 60},
  [12] = {.lex_state = 60},
  [13] = {.lex_state = 60},
  [14] = {.lex_state = 60},
  [15] = {.lex_state = 60},
  [16] = {.lex_state = 60},
  [17] = {.lex_state = 60},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 60},
  [20] = {.lex_state = 4},
  [21] = {.lex_state = 60},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_zinc_block] = ACTIONS(1),
    [sym_trio_block] = ACTIONS(1),
    [sym_list_block] = ACTIONS(1),
    [sym_dict_block] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym_name] = ACTIONS(1),
    [sym_ref] = ACTIONS(1),
    [sym_symbol] = ACTIONS(1),
    [sym_str] = ACTIONS(1),
    [sym_uri] = ACTIONS(1),
    [sym_date_time] = ACTIONS(1),
    [sym_date] = ACTIONS(1),
    [sym_time] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_T] = ACTIONS(1),
    [anon_sym_F] = ACTIONS(1),
    [sym_na] = ACTIONS(1),
    [sym_remove] = ACTIONS(1),
    [sym_list] = ACTIONS(1),
    [sym_dict] = ACTIONS(1),
    [sym_xstr] = ACTIONS(1),
    [sym_indented_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_record] = STATE(10),
    [sym__line] = STATE(4),
    [sym_tag] = STATE(17),
    [sym_block_tag] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_source_file_repeat2] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_separator] = ACTIONS(7),
    [sym_name] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym__newline] = ACTIONS(7),
  },
  [STATE(2)] = {
    [sym__scalar] = STATE(21),
    [sym_bool] = STATE(21),
    [sym_zinc_block] = ACTIONS(11),
    [sym_trio_block] = ACTIONS(11),
    [sym_list_block] = ACTIONS(11),
    [sym_dict_block] = ACTIONS(11),
    [sym_ref] = ACTIONS(13),
    [sym_symbol] = ACTIONS(13),
    [sym_str] = ACTIONS(13),
    [sym_uri] = ACTIONS(13),
    [sym_date_time] = ACTIONS(15),
    [sym_date] = ACTIONS(15),
    [sym_time] = ACTIONS(15),
    [sym_number] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_T] = ACTIONS(17),
    [anon_sym_F] = ACTIONS(17),
    [sym_na] = ACTIONS(15),
    [sym_remove] = ACTIONS(15),
    [sym_list] = ACTIONS(13),
    [sym_dict] = ACTIONS(13),
    [sym_xstr] = ACTIONS(13),
    [sym_raw] = ACTIONS(15),
    [sym_indented_text] = ACTIONS(19),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      aux_sym_source_file_repeat2,
    STATE(10), 1,
      sym_record,
    STATE(12), 1,
      aux_sym_source_file_repeat1,
    STATE(17), 1,
      sym_tag,
    ACTIONS(23), 2,
      sym_separator,
      sym__newline,
    STATE(4), 2,
      sym__line,
      sym_block_tag,
  [30] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(27), 1,
      sym__newline,
    STATE(17), 1,
      sym_tag,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym_separator,
    STATE(5), 3,
      sym__line,
      sym_block_tag,
      aux_sym_record_repeat1,
  [52] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(31), 1,
      sym__newline,
    STATE(17), 1,
      sym_tag,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym_separator,
    STATE(6), 3,
      sym__line,
      sym_block_tag,
      aux_sym_record_repeat1,
  [74] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_name,
    ACTIONS(38), 1,
      sym__newline,
    STATE(17), 1,
      sym_tag,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym_separator,
    STATE(6), 3,
      sym__line,
      sym_block_tag,
      aux_sym_record_repeat1,
  [96] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_source_file_repeat2,
    STATE(10), 1,
      sym_record,
    STATE(17), 1,
      sym_tag,
    STATE(4), 2,
      sym__line,
      sym_block_tag,
  [119] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(9), 1,
      sym_name,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    STATE(9), 1,
      aux_sym_source_file_repeat2,
    STATE(10), 1,
      sym_record,
    STATE(17), 1,
      sym_tag,
    STATE(4), 2,
      sym__line,
      sym_block_tag,
  [142] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 1,
      sym_name,
    STATE(9), 1,
      aux_sym_source_file_repeat2,
    STATE(10), 1,
      sym_record,
    STATE(17), 1,
      sym_tag,
    STATE(4), 2,
      sym__line,
      sym_block_tag,
  [165] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(11), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(48), 2,
      ts_builtin_sym_end,
      sym_name,
    ACTIONS(50), 2,
      sym_separator,
      sym__newline,
  [180] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(23), 2,
      sym_separator,
      sym__newline,
    ACTIONS(43), 2,
      ts_builtin_sym_end,
      sym_name,
  [195] = 4,
    ACTIONS(3), 1,
      sym_comment,
    STATE(12), 1,
      aux_sym_source_file_repeat1,
    ACTIONS(52), 2,
      ts_builtin_sym_end,
      sym_name,
    ACTIONS(54), 2,
      sym_separator,
      sym__newline,
  [210] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(57), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_name,
      sym__newline,
  [220] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(59), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_name,
      sym__newline,
  [230] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(61), 4,
      ts_builtin_sym_end,
      sym_separator,
      sym_name,
      sym__newline,
  [240] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(63), 1,
      anon_sym_COLON,
    ACTIONS(65), 1,
      sym__newline,
  [250] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(67), 1,
      sym__newline,
  [257] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
  [264] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(71), 1,
      sym__newline,
  [271] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(73), 1,
      sym_indented_text,
  [278] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(75), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 30,
  [SMALL_STATE(5)] = 52,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 96,
  [SMALL_STATE(8)] = 119,
  [SMALL_STATE(9)] = 142,
  [SMALL_STATE(10)] = 165,
  [SMALL_STATE(11)] = 180,
  [SMALL_STATE(12)] = 195,
  [SMALL_STATE(13)] = 210,
  [SMALL_STATE(14)] = 220,
  [SMALL_STATE(15)] = 230,
  [SMALL_STATE(16)] = 240,
  [SMALL_STATE(17)] = 250,
  [SMALL_STATE(18)] = 257,
  [SMALL_STATE(19)] = 264,
  [SMALL_STATE(20)] = 271,
  [SMALL_STATE(21)] = 278,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_record, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_record_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(16),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_tag, 3, 0, 2),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_tag, 4, 0, 3),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [69] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bool, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_trio(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "trio",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
