(name) @property
(separator) @punctuation.special
(comment) @comment
(str) @string
(uri) @string.special
(ref) @constant
(symbol) @constant
(number) @number
(date) @number
(time) @number
(date_time) @number
(bool) @boolean
(na) @constant.builtin
(remove) @constant.builtin
(zinc_block) @keyword
(trio_block) @keyword
(indented_text) @string
":" @punctuation.delimiter
