/**
 * LadybugDB Schema Definition
 *
 * Defines the Cypher DDL for the code graph. Mirrors the Prisma CodeNode/CodeEdge
 * models but optimized for graph traversal.
 *
 * Node tables:
 *   - CodeNode: all code symbols (types, functions, methods, fields, etc.)
 *
 * Relationship tables:
 *   - CodeEdge: all relationships (calls, extends, implements, contains, etc.)
 *
 * Shared key: CodeNode.id uses the same 16-char MD5 hash as Prisma's CodeNode.id
 * (generated by generateFunctionId/generateTypeId in fantom-code/types.ts).
 */

import { ladybugExecute, ladybugQuery } from './ladybugConnection.js';
import { createLogger } from '../utils/index.js';

const logger = createLogger('ladybug-schema');

/**
 * DDL statements to create the graph schema.
 * Order matters: node tables before relationship tables.
 */
const SCHEMA_DDL = [
  // Primary node table — all code symbols
  `CREATE NODE TABLE IF NOT EXISTS CodeNode(
    id STRING,
    project_id INT64,
    node_type STRING,
    name STRING,
    qualified_name STRING,
    file_path STRING,
    line_start INT64,
    line_end INT64,
    col_start INT64,
    col_end INT64,
    signature STRING,
    documentation STRING,
    return_type STRING,
    modifiers STRING,
    facets STRING,
    parent_type STRING,
    is_public BOOLEAN,
    is_static BOOLEAN,
    is_abstract BOOLEAN,
    is_virtual BOOLEAN,
    is_override BOOLEAN,
    is_exported BOOLEAN,
    language STRING,
    PRIMARY KEY(id)
  )`,

  // Relationship table — all code edges
  `CREATE REL TABLE IF NOT EXISTS CodeEdge(
    FROM CodeNode TO CodeNode,
    edge_type STRING,
    line_number INT64,
    col_number INT64,
    is_resolved BOOLEAN,
    confidence DOUBLE,
    metadata STRING,
    cross_language BOOLEAN
  )`,
];

/**
 * Check if schema already exists by querying for node table.
 */
async function schemaExists(): Promise<boolean> {
  try {
    await ladybugQuery('MATCH (n:CodeNode) RETURN count(n) AS c');
    return true;
  } catch {
    return false;
  }
}

/**
 * Initialize the LadybugDB schema.
 * Safe to call multiple times — uses IF NOT EXISTS.
 */
export async function initLadybugSchema(): Promise<void> {
  const exists = await schemaExists();
  if (!exists) {
    logger.info('Creating LadybugDB schema...');
    for (const ddl of SCHEMA_DDL) {
      try {
        await ladybugExecute(ddl);
      } catch (err) {
        const msg = String(err);
        if (msg.includes('already exists')) {
          logger.debug(`Table already exists, skipping: ${ddl.slice(0, 60)}...`);
          continue;
        }
        throw err;
      }
    }
    logger.info('LadybugDB schema created successfully');
  } else {
    logger.debug('LadybugDB schema already exists');
  }

  // Idempotent migrations for columns added after initial schema creation.
  const MIGRATIONS = [
    `ALTER TABLE CodeEdge ADD cross_language BOOLEAN DEFAULT false`,
  ];
  for (const ddl of MIGRATIONS) {
    try {
      await ladybugExecute(ddl);
    } catch (err) {
      const msg = String(err).toLowerCase();
      if (
        msg.includes('already exists') ||
        msg.includes('already has property') ||
        msg.includes('duplicate')
      ) continue;
      if (msg.includes('not supported') || msg.includes('syntax')) continue;
      logger.warn(`Schema migration failed (continuing): ${msg.slice(0, 160)}`);
    }
  }
}

/**
 * Drop all graph data for a specific project.
 * Deletes edges first (connected to project nodes), then nodes.
 */
export async function clearProjectGraph(projectId: number): Promise<{
  nodesDeleted: number;
  edgesDeleted: number;
}> {
  // Per-project DB: schema is lazy-initialized inside getProjectConnection,
  // so no separate init step is needed. Just `rm -rf` the project's DB to
  // get a fresh start, then query against it (which recreates schema on
  // first access).
  let nodesBefore: { c: number }[] = [{ c: 0 }];
  try {
    nodesBefore = await ladybugQuery<{ c: number }>(
      projectId,
      `MATCH (n:CodeNode) RETURN count(n) AS c`,
    );
  } catch (err) {
    const msg = String(err);
    if (msg.includes('does not exist')) {
      logger.info(`clearProjectGraph(${projectId}) — table missing, treating as no-op`);
      return { nodesDeleted: 0, edgesDeleted: 0 };
    }
    throw err;
  }

  // Per-project DB: scoped delete is just MATCH (n:CodeNode), no project_id
  // filter needed. Edges first (Kuzu rel-table FK rule).
  await ladybugExecute(projectId, `MATCH (n:CodeNode)-[e:CodeEdge]->() DELETE e`);
  await ladybugExecute(projectId, `MATCH ()-[e:CodeEdge]->(n:CodeNode) DELETE e`);
  await ladybugExecute(projectId, `MATCH (n:CodeNode) DELETE n`);

  const nodesDeleted = nodesBefore[0]?.c ?? 0;
  logger.info(`Cleared graph for project ${projectId}: ${nodesDeleted} nodes removed`);

  return { nodesDeleted, edgesDeleted: 0 };
}

/**
 * Per-project DBs make orphan sweeps unnecessary by construction: every
 * project owns its own Kuzu database, so dropping a project is just
 * `rm -rf .cache/graph/<id>.db` and there is nothing to "orphan". The
 * old `clearOrphanProjectGraphs` was deleted in C4 of the migration —
 * see specs/per-project-graph-migration.md.
 *
 * Kept as a no-op stub for any caller that hasn't been audited yet, so a
 * stray import doesn't crash the server. Will be removed in C5.
 */
export async function clearOrphanProjectGraphs(
  _liveProjectIds: number[],
): Promise<{ orphanProjectIds: number[]; nodesDeleted: number }> {
  return { orphanProjectIds: [], nodesDeleted: 0 };
}

/**
 * Drop all CodeNode/CodeEdge rows for a single source file within a project.
 * Used by per-file incremental re-indexing (reindexChangedFiles): wipe just
 * this file's nodes/edges so they can be rebuilt from a fresh parse, without
 * touching the rest of the project graph.
 *
 * Caveat: edges from OTHER files that targeted symbols in this file will be
 * dangling after this call. They get re-added when the parser produces them
 * for those external files; per-file rebuilds don't fix that. This is
 * acceptable for v1 — full project re-index resolves cleanly.
 */
export async function clearFileGraph(
  projectId: number,
  filePath: string,
): Promise<{ nodesDeleted: number }> {
  const fpEsc = filePath.replace(/'/g, "\\'");

  let nodesBefore: { c: number }[] = [{ c: 0 }];
  try {
    nodesBefore = await ladybugQuery<{ c: number }>(
      projectId,
      `MATCH (n:CodeNode {file_path: '${fpEsc}'}) RETURN count(n) AS c`,
    );
  } catch (err) {
    const msg = String(err);
    if (msg.includes('does not exist')) return { nodesDeleted: 0 };
    throw err;
  }

  // Per-project DB: just match by file_path; project_id filter is implicit.
  await ladybugExecute(
    projectId,
    `MATCH (n:CodeNode {file_path: '${fpEsc}'})-[e:CodeEdge]->() DELETE e`,
  );
  await ladybugExecute(
    projectId,
    `MATCH ()-[e:CodeEdge]->(n:CodeNode {file_path: '${fpEsc}'}) DELETE e`,
  );
  await ladybugExecute(
    projectId,
    `MATCH (n:CodeNode {file_path: '${fpEsc}'}) DELETE n`,
  );

  const nodesDeleted = Number(nodesBefore[0]?.c ?? 0);
  return { nodesDeleted };
}

/**
 * Drop all graph data across all projects.
 */
export async function clearAllGraphData(): Promise<void> {
  await ladybugExecute('MATCH ()-[e:CodeEdge]->() DELETE e');
  await ladybugExecute('MATCH (n:CodeNode) DELETE n');
  logger.info('All graph data cleared');
}

/**
 * Get schema info for diagnostics.
 */
export async function getSchemaInfo(): Promise<{
  nodeCount: number;
  edgeCount: number;
  projectIds: number[];
  nodeTypes: string[];
  edgeTypes: string[];
}> {
  const [nodes, edges, projects, nodeTypes, edgeTypes] = await Promise.all([
    ladybugQuery<{ c: number }>('MATCH (n:CodeNode) RETURN count(n) AS c'),
    ladybugQuery<{ c: number }>('MATCH ()-[e:CodeEdge]->() RETURN count(e) AS c'),
    ladybugQuery<{ pid: number }>('MATCH (n:CodeNode) RETURN DISTINCT n.project_id AS pid'),
    ladybugQuery<{ nt: string }>('MATCH (n:CodeNode) RETURN DISTINCT n.node_type AS nt'),
    ladybugQuery<{ et: string }>('MATCH ()-[e:CodeEdge]->() RETURN DISTINCT e.edge_type AS et'),
  ]);

  return {
    nodeCount: nodes[0]?.c ?? 0,
    edgeCount: edges[0]?.c ?? 0,
    projectIds: projects.map(r => r.pid),
    nodeTypes: nodeTypes.map(r => r.nt),
    edgeTypes: edgeTypes.map(r => r.et),
  };
}
