import { Loc } from "../Loc";
import { Node } from "./Node";
import { Token, TokenType } from "../parser/Token";
import { MethodVar } from "./MethodVar";
import { SlotDef } from "./SlotDef";
import { TypeDef } from "./TypeDef";
import { Block } from "./Block";
import { MethodDef } from "./MethodDef";

/**
 * Expr
 */
abstract class Expr extends Node {
  readonly id: ExprId;
  leave: boolean = true;

  constructor(loc: Loc, id: ExprId) {
    super(loc);
    this.id = id;
  }

  // =======================================================
  // Expr
  // =======================================================

  /**
   * Return this expression as an int literal usable in a tableswitch,
   * or null if this expr doesn't represent a constant Int. Expressions
   * which work as a table switch cases: int literals and enum constants
   */
  asTableSwitchCase(): number | null {
    return null;
  }

  /**
   * If this expression performs assignment, then return
   * the target of that assignment. Otherwise return null
   */
  assignTarget(): Object | null {
    return null;
  }

  /**
   * Return if this expression can be used as the
   * left hand side of an assignment expression
   */
  isAssignable(): boolean {
    return false;
  }

  /**
   * Is this a boolean conditional
   */
  isCond(): boolean {
    return false;
  }

  /**
   * Does this expression make up a complete statement.
   */
  isStmt() {
    return false;
  }

  /**
   * Was this expression generated by the compiler (not necessarily
   * everything auto-generated has this flag true, but we set in
   * cases where error checking needs to be handled special)
   */
  synthetic(): boolean {
    return false;
  }

  /**
   * If this assignemnt expression, then return the
   * result of calling the given function with LHS.
   * otherwise return false
   */
  isDefiniteAssign(f: (lhs: Expr) => boolean) {
    return false;
  }

  /**
   * Return if this expression is guaranteed to
   * sometimes return a null result (safe to invoke as, etc)
   */
  isAlwaysNullable(): boolean {
    return false;
  }

  /**
   * If this as instance of CallExpr return it otherwise null
   */
  asCall(): CallExpr | null {
    return null;
  }

  /**
   * Assignments to instance fields require a temporary local variable
   */
  assignRequiresTempVar(): boolean {
    return false;
  }

  /**
   * Return if this expression represents the same variable or
   * field as that. This is used for self assignment checks
   */
  sameVarAs(that: Expr) {
    return false;
  }

  /**
   * Return this expression as an ExprStmt
   */
  //TODO toStmt(): ExprStmt {
  //TODO   return ExprStmt(this);
  //TODO }

  // =======================================================
  // Tree
  // =======================================================

  //? walk(): Expr {}

  // =======================================================
  // Debug
  // =======================================================

  abstract toStr(): string;
}

enum ExprId {
  nullLiteral, // LiteralExpr
  trueLiteral,
  falseLiteral,
  intLiteral,
  floatLiteral,
  decimalLiteral,
  strLiteral,
  durationLiteral,
  uriLiteral,
  typeLiteral,
  localeLiteral, // LocaleLiteralExpr
  slotLiteral, // SlotLiteralExpr
  rangeLiteral, // RangeLiteralExpr
  listLiteral, // ListLiteralExpr
  mapLiteral, // MapLiteralExpr
  boolNot, // UnaryExpr
  cmpNull,
  cmpNotNull,
  elvis,
  assign, // BinaryExpr
  same,
  notSame,
  boolOr, // CondExpr
  boolAnd,
  isExpr, // TypeCheckExpr
  isnotExpr,
  asExpr,
  coerce,
  call, // CallExpr
  construction,
  shortcut, // ShortcutExpr (has ShortcutOp)
  field, // FieldExpr
  localVar, // LocalVarExpr
  thisExpr, // ThisExpr
  superExpr, // SuperExpr
  itExpr, // ItExpr
  staticTarget, // StaticTargetExpr
  unknownVar, // UnknownVarExpr
  storage,
  ternary, // TernaryExpr
  complexLiteral, // ComplexLiteral
  closure, // ClosureExpr
  dsl, // DslExpr
  throwExpr, // ThrowExpr
}

// =======================================================
// LiteralExpr
// =======================================================

/**
 * LiteralExpr puts an Bool, Int, Float, Str, Duration, Uri,
 * or null constant onto the stack
 */
class LiteralExpr extends Expr {
  val: Object | null;

  constructor(loc: Loc, id: ExprId, val: Object | null) {
    super(loc, id);
    this.val = val;
  }

  static makeNull(loc: Loc): LiteralExpr {
    return new LiteralExpr(loc, ExprId.nullLiteral, null);
  }

  static makeTrue(loc: Loc): LiteralExpr {
    return new LiteralExpr(loc, ExprId.trueLiteral, true);
  }

  static makeFalse(loc: Loc): LiteralExpr {
    return new LiteralExpr(loc, ExprId.falseLiteral, false);
  }

  static makeStr(loc: Loc, val: string): LiteralExpr {
    return new LiteralExpr(loc, ExprId.strLiteral, val);
  }

  override isAlwaysNullable(): boolean {
    return this.id == ExprId.nullLiteral;
  }

  override asTableSwitchCase(): number | null {
    return this.val as number;
  }

  toStr(): string {
    switch (this.id) {
      case ExprId.nullLiteral:
        return "null";
      case ExprId.strLiteral:
        return '"' + this.val!.toString().replace("\n", "\\n") + '"';
      case ExprId.typeLiteral:
        return "${val}#";
      case ExprId.uriLiteral:
        return "`$val`";
      default:
        return this.val!.toString();
    }
  }
}

// =======================================================
// LocaleLiteralExpr
// =======================================================

/**
 * LocaleLiteralExpr: podName::key=defVal
 */
class LocaleLiteralExpr extends Expr {
  pattern: string;
  key: string;
  podName!: string | null;
  def!: string | null;

  constructor(loc: Loc, pattern: string) {
    super(loc, ExprId.localeLiteral);
    this.pattern = pattern;
    this.key = pattern;
    let eq = pattern.indexOf("=");
    if (eq != null) {
      this.key = pattern.slice(0, eq);
      this.def = pattern.slice(eq + 1);
    }

    let colons = this.key.indexOf("::");
    if (colons != null) {
      this.podName = this.key.slice(0, colons);
      this.key = this.key.slice(colons + 2);
    }
  }

  toStr(): string {
    return `<${this.pattern}>`;
  }
}

// =======================================================
// SlotLiteralExpr
// =======================================================

/**
 * SlotLiteralExpr
 */
class SlotLiteralExpr extends Expr {
  name: string;
  constructor(loc: Loc, name: string) {
    super(loc, ExprId.slotLiteral);
    this.name = name;
  }

  override toStr(): string {
    return "";
  }
}

// =======================================================
// RangeLiteralExpr
// =======================================================

/**
 * RangeLiteralExpr creates a Range instance
 */
class RangeLiteralExpr extends Expr {
  start: Expr;
  end: Expr;
  exclusive: boolean;

  constructor(loc: Loc, start: Expr, end: Expr, exclusive: boolean) {
    super(loc, ExprId.rangeLiteral);
    this.start = start;
    this.end = end;
    this.exclusive = exclusive;
  }

  toStr(): string {
    if (this.exclusive) return `${this.start}...${this.end}`;
    else return `${this.start}..${this.end}`;
  }
}

// =======================================================
// ListLiteralExpr
// =======================================================

/**
 * ListLiteralExpr creates a List instance
 */
class ListLiteralExpr extends Expr {
  vals: Expr[] = [];

  constructor(loc: Loc) {
    super(loc, ExprId.listLiteral);
  }

  static makeFor(loc: Loc, vals: Expr[]) {
    let list = new ListLiteralExpr(loc);
    list.vals = vals;
    return list;
  }

  override toStr(): string {
    return this.format(e => e.toStr());
  }

  format(f: (e: Expr) => string): string {
    let s = "";
    s += "[";
    if (this.vals.length === 0) {
      s += ",";
    } else {
      this.vals.forEach((v: Expr, i: number) => {
        if (i > 0) {
          s += ",";
        }
        s += f(v);
      });
    }
    s += "]";
    return s;
  }
}

// =======================================================
// MapLiteralExpr
// =======================================================

/**
 * mapLiteralExpr creates a Map instance
 */
class MapLiteralExpr extends Expr {
  keys: Expr[] = [];
  vals: Expr[] = [];

  constructor(loc: Loc) {
    super(loc, ExprId.mapLiteral);
  }

  override toStr(): string {
    return this.format(e => e.toStr());
  }

  format(f: (e: Expr) => string): string {
    let s = "";

    s += "[";
    if (this.vals.length === 0) {
      s += ":";
    } else {
      this.keys.forEach((k, i) => {
        if (i > 0) {
          s += ",";
        }
        s += f(this.keys[i]);
        s += ":";
        s += f(this.vals[i]);
      });
    }
    s += "]";
    return s;
  }
}

// =======================================================
// UnaryExpr
// =======================================================

/**
 * UnaryExpr is used for unary expressions including !, +.
 * Not that - is mapped to negate() as a shortcut method
 */
class UnaryExpr extends Expr {
  opToken: Token; // operator token type (Token.bang, etc)
  operand: Expr; // operand expression

  constructor(loc: Loc, id: ExprId, opToken: Token, operand: Expr) {
    super(loc, id);
    this.opToken = opToken;
    this.operand = operand;
  }

  override toStr(): string {
    if (this.id == ExprId.cmpNull) {
      return this.operand.toStr() + " == null";
    } else if (this.id === ExprId.cmpNotNull) {
      return this.operand.toStr() + " != null";
    } else return this.opToken.toStr() + this.operand.toStr();
  }
}

// =======================================================
// Binary Expression
// =======================================================

/**
 * BinaryExpr is sued for binary expression with a left hand side and a
 * right hand side including assignment. Note that many common binary
 * operations are actually modeled as a shortcutExpr ro anble method based
 * operator overloading.
 */
class BinaryExpr extends Expr {
  opToken: Token;
  lhs: Expr;
  rhs: Expr;
  //? tempVar: MethodVar | null;

  constructor(lhs: Expr, opToken: Token, rhs: Expr) {
    super(lhs.loc, opToken.toExprId());
    this.lhs = lhs;
    this.opToken = opToken;
    this.rhs = rhs;
  }

  static makeAssign(lhs: Expr, rhs: Expr, leave: boolean = false): BinaryExpr {
    let biExpr = new BinaryExpr(lhs, new Token(TokenType.assign), rhs);
    biExpr.leave = leave;
    return biExpr;
  }

  assignTarget(): Object | null {
    return this.id === ExprId.assign ? this.lhs : null;
  }

  isStmt(): boolean {
    return this.id === ExprId.assign;
  }

  isDefiniteAssign(f: (lhs: Expr) => boolean): boolean {
    if (this.id === ExprId.assign && f(this.lhs)) {
      return true;
    }
    return this.rhs.isDefiniteAssign(f);
  }

  toStr(): string {
    return `(${this.lhs} ${this.opToken} ${this.rhs})`;
  }
}

// =======================================================
// CondExpr
// =======================================================

/**
 * CondExpr is used for || and && short-circuit boolean consditionals
 */
class CondExpr extends Expr {
  opToken: Token; // operator token type (Token.and, etc)
  operands: Expr[]; // list of operands

  constructor(first: Expr, opToken: Token) {
    super(first.loc, opToken.toExprId());
    this.opToken = opToken;
    this.operands = [first];
  }

  override isCond(): boolean {
    return true;
  }

  override toStr(): string {
    return this.operands.join(` ${this.opToken} `);
  }
}

// =======================================================
// NameExpr
// =======================================================

/**
 * NameExpr is the base class for an identifier expression which has
 * an optional base expression. NameExpr is the base class for
 * UnkownVarExpr and CallExpr which are resolved via CallResolver
 */
abstract class NameExpr extends Expr {
  target: Expr | null; // base target expression or null
  name: string | null; // name of variable (local/field/method)
  isSafe: boolean; // if ?. operator

  constructor(loc: Loc, id: ExprId, target: Expr | null, name: string | null) {
    super(loc, id);
    this.target = target;
    this.name = name;
    this.isSafe = false;
  }

  override isAlwaysNullable(): boolean {
    return this.isSafe;
  }

  toStr(): string {
    if (this.target != null) {
      return this.target.toStr() + (this.isSafe ? "?." : ".") + this.name;
    } else {
      return this.name!;
    }
  }
}

// =======================================================
// UnkownVarExpr
// =======================================================

/**
 *UnknownVarExpr is a place holder in the AST for a variable until
 * we can figure out what it references: local or slot.  We also use
 * this class for storage operators before they are resolved to a field.
 */
class UnknownVarExpr extends NameExpr {
  constructor(
    loc: Loc,
    target: Expr | null,
    name: string,
    id: ExprId = ExprId.unknownVar
  ) {
    super(loc, id, target, name);
  }
}

// =======================================================
// CallExpr
// =======================================================

/**
 * CallExpr is a method call.
 */
//todo still has somethings undone
class CallExpr extends NameExpr {
  args: Expr[]; // Expr[] arguments to pass
  isDynamic: boolean; // true if this is a -> dynamic call
  isCtorChain: boolean; // true if this is MethodDef.ctorChain call
  noParens: boolean; // was this call accessed without parens
  isCallOp: boolean; // was this 'target()' (instead of 'target.name()')
  isItAdd: boolean; // if using comma operator
  //? CMethod? method     // resolved method
  override synthetic(): boolean {
    return false;
  }

  constructor(
    loc: Loc,
    target: Expr | null = null,
    name: string | null = null,
    id: ExprId = ExprId.call
  ) {
    super(loc, id, target, name);
    this.args = [];
    this.isDynamic = false;
    this.isSafe = false;
    this.isCtorChain = false;
  }

  //? override toStr(): string {
  //?   return toCallStr(true);
  //? }

  override isDefiniteAssign(f: (lhs: Expr) => boolean): boolean {
    if (this.target != null && this.target.isDefiniteAssign(f)) {
      return true;
    }
    return this.args.some(arg => arg.isDefiniteAssign(f));
  }

  //?override Bool isStmt()
  //?{
  //?  // stand alone constructor is not a valid stmt
  //?  if (method.isCtor) return false
  //?
  //?  // with block applied to stand alone constructor is not valid stmt
  //?  if (method.name == "with" && target is CallExpr && ((CallExpr)target).method.isCtor)
  //?    return false
  //?
  //?  // consider any other call a stand alone stmt
  //?  return true
  //?}

  asCall(): CallExpr | null {
    return this;
  }

  isCompare(): boolean {
    return false;
  }

  //? Expr targetx()
  //? {
  //?   if (target != null) return target
  //?   if (method.isStatic || method.isCtor) return StaticTargetExpr(loc, method.parent)
  //?   throw Err("Call missing target: $this")
  //? }
}

// =======================================================
// ShortcutExpr
// =======================================================

/**
 * ShortcutExpr is used for operator expressions which are a shortcut
 * to a method call:
 *   a + b     =>  a.plus(b)
 *   a - b     =>  a.minus(b)
 *   a * b     =>  a.mult(b)
 *   a / b     =>  a.div(b)
 *   a % b     =>  a.mod(b)
 *   a[b]      =>  a.get(b)
 *   a[b] = c  =>  a.set(b, c)
 *   -a        =>  a.negate()
 *   ++a, a++  =>  a.increment()
 *   --a, a--  =>  a.decrement()
 *   a == b    =>  a.equals(b)
 *   a != b    =>  ! a.equals(b)
 *   a <=>     =>  a.compare(b)
 *   a > b     =>  a.compare(b) > 0
 *   a >= b    =>  a.compare(b) >= 0
 *   a < b     =>  a.compare(b) < 0
 *   a <= b    =>  a.compare(b) <= 0
 */
class ShortcutExpr extends CallExpr {
  op!: ShortcutOp;
  opToken!: Token;
  isPostfixLeave: boolean | null = false; // x++ or x-- (must have Expr.leave set too)
  //? tempVar: MethodVar | null; // temp local var to store += to field/indexed

  constructor(loc: Loc) {
    super(loc, null, null, ExprId.shortcut);
  }

  static makeUnary(loc: Loc, opToken: Token, operand: Expr): ShortcutExpr {
    let expr = new ShortcutExpr(loc);
    expr.op = opToken.toShortcutOp(1);
    expr.opToken = opToken;
    expr.name = expr.op.methodName;
    expr.target = operand;
    return expr;
  }

  static makeBinary(lhs: Expr, opToken: Token, rhs: Expr): ShortcutExpr {
    let expr = new ShortcutExpr(lhs.loc);
    expr.op = opToken.toShortcutOp(2);
    expr.opToken = opToken;
    expr.name = expr.op.methodName;
    expr.target = lhs;
    expr.args.push(rhs);
    return expr;
  }

  static makeGet(loc: Loc, target: Expr, index: Expr): ShortcutExpr {
    let expr = new ShortcutExpr(loc);
    expr.op = ShortcutOp.get();
    expr.opToken = new Token(TokenType.lbracket);
    expr.name = expr.op.methodName;
    expr.target = target;
    expr.args.push(index);
    return expr;
  }

  static makeFrom(from: ShortcutExpr) {
    let expr = new ShortcutExpr(from.loc);
    expr.op = from.op;
    expr.opToken = from.opToken;
    expr.name = from.name;
    expr.target = from.target;
    expr.args = from.args;
    expr.isPostfixLeave = from.isPostfixLeave;
    return expr;
  }

  override assignRequiresTempVar(): boolean {
    return this.isAssignable();
  }

  override assignTarget(): Object | null {
    return this.isAssign() ? this.target : null;
  }

  override isAssignable(): boolean {
    return this.op?.symbol === ShortcutOp.get()?.symbol;
  }

  override isCompare(): boolean {
    return (
      this.op?.symbol === ShortcutOp.eq().symbol ||
      this.op?.symbol === ShortcutOp.cmp().symbol
    );
  }

  override isStmt(): boolean {
    return this.isAssign() || this.op?.symbol === ShortcutOp.set().symbol;
  }

  isAssign(): boolean {
    return this.opToken.isAssign || this.opToken.isIncrementOrDecrement();
  }

  override toStr(): string {
    if (this.op?.symbol == ShortcutOp.get().symbol)
      return `${this.target}[${this.args.at(1)}]`;
    if (this.op?.symbol == ShortcutOp.increment().symbol)
      return this.isPostfixLeave ? `${this.target}++` : `++${this.target}`;
    if (this.op?.symbol == ShortcutOp.decrement().symbol)
      return this.isPostfixLeave ? `${this.target}--` : `--${this.target}`;
    if (this.isAssign())
      return `${this.target} ${this.opToken} ${this.args.at(1)}`;
    if (this.op.degree == 1) return `${this.opToken}${this.target}`;
    if (this.op.degree == 2)
      return `(${this.target} ${this.opToken} ${this.args.at(1)})`;
    return super.toStr();
  }
}

/**
 * IndexedAssignExpr is a subclass of ShortcutExpr used
 * in situations like x[y] += z where we need keep of two
 * extra scratch variables and the get's matching set method.
 * Note this class models the top x[y] += z, NOT the get target
 * which is x[y].
 *
 * In this example, IndexedAssignExpr shortcuts Int.plus and
 * its target shortcuts List.get:
 *   x := [2]
 *   x[0] += 3
 */
class IndexedAssignExpr extends ShortcutExpr {
  static makeFrom(from: ShortcutExpr) {
    return super.makeFrom(from);
  }
}

// =======================================================
// FieldsExpr
// =======================================================

/**
 * FieldExpr is used for a field variable access.
 */
class FieldExpr extends NameExpr {
  useAccessor: boolean; // false if access using '&' storage operator

  constructor(
    loc: Loc,
    target: Expr | null = null,
    useAccessor: boolean = true
  ) {
    super(loc, ExprId.field, target, null);
    this.useAccessor = useAccessor;
    this.isSafe = false;
  }

  override isAssignable(): boolean {
    return true;
  }

  override toStr(): string {
    let s = "";
    if (this.target != null) {
      s += this.target;
      s += ".";
    }
    if (this.isSafe) {
      s += "?";
    }
    if (!this.useAccessor) {
      s += "@";
    }
    s += this.name;
    return s;
  }
}

// =======================================================
// LocalVarExpr
// =======================================================

/**
 * LocalVarExpr is used to access a local variable stored in a register
 */
class LocalVarExpr extends Expr {
  vari?: MethodVar | null; // bound variable
  unwrap: boolean = true; // if hoisted onto heap with wrapper

  constructor(loc: Loc, vari: MethodVar | null, id: ExprId = ExprId.localVar) {
    super(loc, id);
    if (vari !== null) {
      this.vari = vari;
      //? this.ctype = var.ctype
    }
  }

  static makeNoUnwrap(loc: Loc, vari: MethodVar) {
    let self = new LocalVarExpr(loc, vari, ExprId.localVar);
    self.unwrap = false;
    return self;
  }

  override isAssignable(): boolean {
    return true;
  }

  //todo override Bool assignRequiresTempVar() { var.usedInClosure }

  //todo override Bool sameVarAs(Expr that)
  //todo {
  //todo   x := that as LocalVarExpr
  //todo   if (x == null) return false
  //todo   if (var?.usedInClosure != x?.var?.usedInClosure) return false
  //todo   return register == x.register
  //todo }

  register(): number {
    return this.vari?.register || 0;
  }

  name(): string {
    return this.vari?.name || "";
  }

  override toStr(): string {
    if (this.vari == null) return "???";
    return this.vari.name;
  }
}

// =======================================================
// ThisExpr
// =======================================================

/**
 * ThisExpr models the "this" keyword to access the implicit this
 * local variable always stored in register zero.
 */
class ThisExpr extends LocalVarExpr {
  _register = 0;
  constructor(loc: Loc) {
    super(loc, null, ExprId.thisExpr);
  }

  override isAssignable(): boolean {
    return false;
  }

  override register(): number {
    return this._register;
  }

  override toStr(): string {
    return "this";
  }
}

// =======================================================
// SuperExpr
// =======================================================

/**
 * SuperExpr is used to access super class slots.  It always references
 * the implicit this local variable stored in register zero, but the
 * super class's slot definitions.
 */
class SuperExpr extends LocalVarExpr {
  _register = 0;

  constructor(loc: Loc) {
    super(loc, null, ExprId.superExpr);
  }

  override isAssignable(): boolean {
    return false;
  }

  register(): number {
    return this._register;
  }

  override toStr(): string {
    return "super";
  }
}

// =======================================================
// ItExpr
// =======================================================

/**
 * ItExpr models the "it" keyword to access the implicit
 * target of an it-block
 */
class ItExpr extends LocalVarExpr {
  constructor(loc: Loc) {
    super(loc, null, ExprId.itExpr);
  }

  override isAssignable(): boolean {
    return false;
  }

  override register() {
    return 1;
  } // Void doCall(Type it)

  override name(): string {
    return "it";
  }

  override toStr(): string {
    return "it";
  }
}

// =======================================================
// StaticTargetExpr
// =======================================================

/**
 * StaticTargetExpr wraps a type reference as an Expr for use as
 * a target in a static field access or method call
 */
class StaticTargetExpr extends Expr {
  constructor(loc: Loc) {
    super(loc, ExprId.staticTarget);
  }

  //? override Bool sameVarAs(Expr that)
  //? {
  //?   that.id === ExprId.staticTarget && ctype == that.ctype
  //? }

  override toStr(): string {
    return "";
  }
}

// =======================================================
// TypeCheckExpr
// =======================================================

/**
 * TypeCheckExpr is an expression which is compsoed of an arb
 */
class TypeCheckExpr extends Expr {
  target: Expr;

  _synthetic = false;

  override synthetic(): boolean {
    return this._synthetic;
  }

  constructor(loc: Loc, id: ExprId, target: Expr) {
    super(loc, id);

    this.target = target;
  }

  static coerce(target: Expr): TypeCheckExpr {
    const expr = new TypeCheckExpr(target.loc, ExprId.coerce, target);
    expr._synthetic = true;
    return expr;
  }

  override isStmt(): boolean {
    return this.id === ExprId.coerce && this.target.isStmt();
  }

  override isAlwaysNullable(): boolean {
    return this.id === ExprId.asExpr;
  }

  override isDefiniteAssign(f: (lhs: Expr) => boolean): boolean {
    return this.target.isDefiniteAssign(f);
  }

  opStr(): string {
    switch (this.id) {
      case ExprId.isExpr:
        return "is";
      case ExprId.isnotExpr:
        return "isnot";
      case ExprId.asExpr:
        return "as";
      default:
        throw new Error(`${this.id}`);
    }
  }

  override toStr(): string {
    switch (this.id) {
      case ExprId.isExpr:
        return `(${this.target})`;
      case ExprId.isnotExpr:
        return `(${this.target})`;
      case ExprId.asExpr:
        return `(${this.target})`;
      case ExprId.coerce:
        return `(${this.target})`;
      default:
        throw Error(`${this.id}`);
    }
  }
}

/**
 * TernaryExpr is used for the ternary expression [cond] ? [true] : [false]
 */
class TernaryExpr extends Expr {
  condition: Expr;
  trueExpr: Expr;
  falseExpr: Expr;

  constructor(condition: Expr, trueExpr: Expr, falseExpr: Expr) {
    super(condition.loc, ExprId.ternary);
    this.condition = condition;
    this.trueExpr = trueExpr;
    this.falseExpr = falseExpr;
  }

  toStr(): string {
    return `${this.condition} ? ${this.trueExpr} : ${this.falseExpr}`;
  }
}

// =======================================================
// ComplexLiteral
// =======================================================

class ComplexLiteral extends Expr {
  names: string[];
  vals: Expr[];

  constructor(loc: Loc) {
    super(loc, ExprId.complexLiteral);
    this.names = [];
    this.vals = [];
  }

  override toStr(): string {
    return this.doToStr(e => e.toStr());
  }

  doToStr(f: (e: Expr) => string): string {
    let s = "";
    s += "$ctype {";
    this.names.forEach((n, i) => {
      n += `${n} = ${f(this.vals[i])};`;
    });
    s += "}";
    return s;
  }
}

// =======================================================
// ClosureExpr
// =======================================================
class ClosureExpr extends Expr {
  // Parse
  enclosingType!: TypeDef; // enclosing class
  enclosingSlot!: SlotDef; // enclosing method or field initializer
  enclosingClosure?: ClosureExpr | null; // if nested closure
  //FuncType signature            // function signature
  code?: Block | null; // moved into a MethodDef in InitClosures
  name!: string; // anonymous class name
  isItBlock!: boolean; // does closure have implicit it scope

  // InitClosures
  substitute?: CallExpr | null; // expression to substitute during assembly
  cls?: TypeDef | null; // anonymous class which implements the closure
  call?: MethodDef | null; // anonymous class's call() with code
  doCall?: MethodDef | null; // anonymous class's doCall() with code

  // ResolveExpr
  enclosingVars?: Map<string, MethodVar> | null; // my parent methods vars in scope
  setsConst!: boolean; // sets one or more const fields (CheckErrors)
  //? CType? itType                  // type of implicit it

  constructor(
    loc: Loc,
    enclosingType: TypeDef,
    enclosingSlot: SlotDef,
    enclosingClosure: ClosureExpr | null,
    //?FuncType signature,
    name: string
  ) {
    super(loc, ExprId.closure);
    //?  this.ctype = signature;
    this.enclosingType = enclosingType;
    this.enclosingSlot = enclosingSlot;
    this.enclosingClosure = enclosingClosure;
    //? this.signature = signature;
    this.name = name;
  }

  //todo outerThisField() {
  //todo   if (enclosingSlot.isStatic) throw Err("Internal error: $loc.toLocStr");
  //todo   return ClosureVars.makeOuterThisField(this);
  //todo }

  override toStr(): string {
    return ` { ... }`;
  }

  //todo override Bool isDefiniteAssign(|Expr lhs->Bool| f)
  //todo {
  //todo   // at this point, we have moved code into doCall method
  //todo   if (doCall == null) return false
  //todo   return doCall.code.isDefiniteAssign(f)
  //todo }
}

// =======================================================
// DSL
// =======================================================
/**
 * DslExpr is an embedded Domain Specific Language which
 * is parsed by a DslPlugin.
 */
class DslExpr extends Expr {
  src: string; // anchorType <|src|>
  srcLoc: Loc; // location of first char of src
  leadingTabs!: number; // number of leading tabs on original Fantom line
  leadingSpaces!: number; // number of leading non-tab chars on original Fantom line

  constructor(loc: Loc, srcLoc: Loc, src: string) {
    super(loc, ExprId.dsl);
    this.src = src;
    this.srcLoc = srcLoc;
  }

  override toStr(): string {
    return `$string <|${this.src}|>`;
  }
}

// =======================================================
// ThrowExpr
// =======================================================

class ThrowExpr extends Expr {
  exception: Expr; // exception to throw

  constructor(loc: Loc, execption: Expr) {
    super(loc, ExprId.throwExpr);
    this.exception = execption;
  }
  override toStr(): string {
    return `throw ${this.exception}`;
  }
}

class ShortcutOp {
  readonly degree: number;
  readonly methodName: string;
  readonly isOperator: boolean;
  readonly symbol: string;

  constructor(
    degree: number,
    symbol: string,
    methodName: string,
    isOperator: boolean = false
  ) {
    this.degree = degree;
    this.symbol = symbol;
    this.methodName = methodName;
    this.isOperator = isOperator;
  }

  static plus(): ShortcutOp {
    return new ShortcutOp(2, "+", "plus", true);
  }

  static minus(): ShortcutOp {
    return new ShortcutOp(2, "-", "minus", true);
  }

  static mult(): ShortcutOp {
    return new ShortcutOp(2, "*", "mult", true);
  }

  static div(): ShortcutOp {
    return new ShortcutOp(2, "/", "div", true);
  }

  static mod(): ShortcutOp {
    return new ShortcutOp(2, "%", "mod", true);
  }

  static negate(): ShortcutOp {
    return new ShortcutOp(1, "-", "negate", true);
  }

  static increment(): ShortcutOp {
    return new ShortcutOp(1, "++", "increment", true);
  }

  static decrement(): ShortcutOp {
    return new ShortcutOp(1, "--", "decrement", true);
  }

  static eq(): ShortcutOp {
    return new ShortcutOp(1, "==", "equals", false);
  }

  static cmp(): ShortcutOp {
    return new ShortcutOp(1, "<=>", "compare", false);
  }

  static get(): ShortcutOp {
    return new ShortcutOp(2, "[]", "get", true);
  }
  static set() {
    return new ShortcutOp(3, "[]=", "set", true);
  }
  static add() {
    return new ShortcutOp(2, ",", "add", true);
  }

  static fromPrefix(prefix: string): ShortcutOp | null {
    return this.prefixes.get(prefix) ?? null;
  }

  static readonly prefixes: Map<string, ShortcutOp> = (() => {
    const map = new Map<string, ShortcutOp>();
    const ops = [
      ShortcutOp.plus(),
      ShortcutOp.minus(),
      ShortcutOp.mult(),
      ShortcutOp.div(),
      ShortcutOp.mod(),
      ShortcutOp.negate(),
      ShortcutOp.increment(),
      ShortcutOp.decrement(),
      ShortcutOp.eq(),
      ShortcutOp.cmp(),
      ShortcutOp.get(),
      ShortcutOp.set(),
      ShortcutOp.add(),
    ];
    ops.forEach(op => map.set(op.methodName, op));
    return map;
  })();
}

export {
  Expr,
  ExprId,
  LiteralExpr,
  LocaleLiteralExpr,
  SlotLiteralExpr,
  RangeLiteralExpr,
  ListLiteralExpr,
  MapLiteralExpr,
  UnaryExpr,
  BinaryExpr,
  CondExpr,
  NameExpr,
  UnknownVarExpr,
  CallExpr,
  ShortcutExpr,
  IndexedAssignExpr,
  FieldExpr,
  LocalVarExpr,
  ThisExpr,
  SuperExpr,
  ItExpr,
  StaticTargetExpr,
  TypeCheckExpr,
  TernaryExpr,
  ComplexLiteral,
  ClosureExpr,
  DslExpr,
  ThrowExpr,
  ShortcutOp,
};
