import { Loc } from "../Loc";

/**
 * Node is the base class of all classes which represent a node
 * in the abstract syntax tree generated by the parser
 */
abstract class Node {
  loc: Loc;

  constructor(loc: Loc) {
    this.loc = loc;
  }
}

export { Node };
